services:
  bakpcascade:
    restart: always
    container_name: bakpcascade
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/         # Mount Yii2 web root
    ports:
      - "350:80"   # Map external port 300 to container's port 80
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true